config/routes.rb
Her30degtest::Application.routes.draw do
  root :to => "leagues#index"
  match 'logout' => 'pages'
  match 'users/:id/join_league' => 'users#join_league'
  match 'leagues/:id/compete' => 'leagues#compete'
  match 'pages/login' => 'pages#login'
  match 'pages/search' => 'pages#search'
  match 'pages/authenticate' => 'pages#authenticate'
  
  resources :pages
  
  resources :users do
    member do
      get 'remove_from_league'
      get 'join_league'
    end
  end

  resources :leagues do
    member do
      get 'compete'
    end
  end

  match ':controller(/:action(/:id(.:format)))'
  

end

app/models/league.rb
class League < ActiveRecord::Base
  has_many :rankings
  has_many :users, :through => :rankings
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  # GET /leagues
  # GET /leagues.xml
  def index
    @leagues = League.all
    @leagues.sort! do |a,b|
      comp = (b.year <=> a.year)
      comp.zero? ? (sem2int(b.semester) <=> sem2int(a.semester)) : comp
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @leagues }
    end
  end



  def compete
    @league = League.find(params[:id])
    
    user1won = params[:win]
    @user1 = User.where(:member_id => params[:q1])[0]
    @user2 = User.where(:member_id => params[:q2])[0]
    
    if @user1 == nil || @user2 == nil
      @msg = 'User does not exist'
    else
    
      if user1won != "draw"
      
        r1 = @user1.rankings.where(:league_id => params[:id])[0]
        r2 = @user2.rankings.where(:league_id => params[:id])[0]
    
        rank1 = Float(r1.ranking)
        rank2 = Float(r2.ranking)
    
        est1 = 1 / Float(1 + 10 ** ((rank2 - rank1) / 400))
        est2 = 1 / Float(1 + 10 ** ((rank1 - rank2) / 400))
        
        if user1won == "true"
          sc1 = 1
          sc2 = 0
        else
          sc1 = 0
          sc2 = 1
        end
    
        r1.ranking = Integer((rank1 + 10 * (sc1 - est1)).round)
        r2.ranking = Integer((rank2 + 10 * (sc2 - est2)).round) 
    
        r1.save
        r2.save
      end
    
      @msg = 'Match outcome was recodred.'
    end
    
    respond_to do |format|
      format.html { redirect_to(@league, :notice => @msg) }
    end
  end

  # GET /leagues/1
  # GET /leagues/1.xml
  def show
    @league = League.find(params[:id])
    @users = @league.users
    @users.sort! { |a,b| b.rankings.where(:league_id => @league.id)[0].ranking <=> 
      a.rankings.where(:league_id => @league.id)[0].ranking }
      
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @league }
    end
  end

  # GET /leagues/new
  # GET /leagues/new.xml
  def new
    @league = League.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @league }
    end
  end

  # GET /leagues/1/edit
  def edit
    @league = League.find(params[:id])
  end

  # POST /leagues
  # POST /leagues.xml
  def create
    @league = League.new(params[:league])

    respond_to do |format|
      if @league.save
        format.html { redirect_to(@league, :notice => 'League was successfully created.') }
        format.xml  { render :xml => @league, :status => :created, :location => @league }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @league.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /leagues/1
  # PUT /leagues/1.xml
  def update
    @league = League.find(params[:id])

    respond_to do |format|
      if @league.update_attributes(params[:league])
        format.html { redirect_to(@league, :notice => 'League was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @league.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1
  # DELETE /leagues/1.xml
  def destroy
    @league = League.find(params[:id])
    @league.destroy

    respond_to do |format|
      format.html { redirect_to(leagues_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.erb
<%= form_for(@league) do |f| %>
  <% if @league.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
      <% @league.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game %><br />
    <%= f.text_field :game %>
  </div>

  <div class="field">
    <%= f.label :year %><br />
    <%= f.text_field :year %>
  </div>

  <div class="field">
	<%= f.label :semester %><br />
	<%= f.select(:semester, options_for_select(['Winter', 'Spring','Summer'])) %>
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leagues/compete.html.erb
Congrats!

app/views/leagues/edit.html.erb
<h1>Editing league</h1>

<%= render 'form' %>

<%= link_to 'Show', @league %> |
<%= link_to 'Back', leagues_path %>

app/views/leagues/index.html.erb
<script>changeMenuTab("leaguesTab");</script>
<center>
	<h1>Leagues</h1>
	<%= link_to 'New League', new_league_path %><br /><br />
	<table>
	<% @leagues.each do |league| %>
	  <tr>	
	    <td><center><%= link_to league.game, league %></center></td>
	  </tr>
	  <tr>
		<td><center><%= league.semester %> <%= league.year %></center></td>
	  </tr>
	  <tr>
		<td>participants: <%= league.users.count %></td>
	  </tr>
	  <tr>
		<td><br /></td>
	  </tr>	
	<% end %>
	</table>

app/views/leagues/new.html.erb
<h1>New league</h1>

<%= render 'form' %>

<%= link_to 'Back', leagues_path %>

app/views/leagues/show.html.erb
<center>
	<p>
	  <h1><%= @league.game %></h1>
	  <%= @league.semester %> <%= @league.year %>
	</p>

	<table align="center" cellpadding="6px">
	  <tr>
		<th>Rank</th>
	    <th>Name</th>
		<th>ID</th>
	  </tr>
		
		<% @i = 0 %>
		<% for u in @users %>
			<% @i += 1 %>
		  <tr>
			<td><center><%= @i %></center></td>
		    <td><%= link_to u.name, u %></td>
		    <td><%= u.member_id %></td>
		  </tr>
		<% end %>

	</table>
	<br /><br />
	<p>
		Record Competition Outcome:
		<%= form_tag(compete_league_path , :method => "post") do %>
			<%= label_tag(:q1, "Player 1 ID:") %>
			<%= text_field_tag(:q1) %> <br /><br />
			<%= label_tag(:q2, "Player 2 ID:") %>
			<%= text_field_tag(:q2) %> <br /><br />
			<%= radio_button_tag(:win, "true") %>
			<%= label_tag(:win, "Player 1 won") %>
			<%= radio_button_tag(:win, "draw") %>
			<%= label_tag(:win, "Draw") %>
			<%= radio_button_tag(:win, "false") %>
			<%= label_tag(:win, "Player 2 won") %><br /><br />
			<%= submit_tag("Go!") %>
		<% end %>
	</p>	
</center>


<br /><br /><br />
<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_league_path(@league) %> |
<%= link_to 'Remove', @league, :confirm => 'Are you sure?', :method => :delete %> |
<%= link_to 'Back', leagues_path %> 