config/routes.rb
Her30degtest::Application.routes.draw do
  root :to => "leagues#index"
  match 'logout' => 'pages'
  match 'users/:id/join_league' => 'users#join_league'
  match 'leagues/:id/compete' => 'leagues#compete'
  match 'pages/login' => 'pages#login'
  match 'pages/search' => 'pages#search'
  match 'pages/authenticate' => 'pages#authenticate'
  
  resources :pages
  
  resources :users do
    member do
      get 'remove_from_league'
      get 'join_league'
    end
  end

  resources :leagues do
    member do
      get 'compete'
    end
  end

  match ':controller(/:action(/:id(.:format)))'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :rankings
  has_many :leagues, :through => :rankings
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  def remove_from_league
    @user = User.find(params[:id])
    l = League.find(params[:lid])
    ls = User.find(params[:id]).leagues
    if ls.include?(l)
      User.find(params[:id]).leagues.delete(League.find(params[:lid]))
      @msg = "User is now removed from this league"
    else
      @msg = "User is not participating in this league"
    end
    
    respond_to do |format|
      format.html { redirect_to(@user, :notice => @msg) }
    end
  end

  def join_league
    @user = User.find(params[:id])
    ls = User.find(params[:id]).leagues
    l = League.find(params[:lid])
    if (ls.include?(l))
      @msg = "User already participating in this league"
    else
      User.find(params[:id]).leagues.push(League.find(params[:lid]))
      r = Ranking.where(:user_id => params[:id], :league_id => params[:lid])[0]
      r.ranking = 1000
      r.save
      
      @msg = "User is now joined."
    end
    respond_to do |format|
      format.html { redirect_to(@user, :notice => @msg) }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])
    
    @leagues = @user.leagues
    @leagues.sort! do |a,b|
      comp = (b.year <=> a.year)
      comp.zero? ? (sem2int(b.semester) <=> sem2int(a.semester)) : comp
    end
    
    @other_leagues = League.all - @leagues

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])
    @user.play_count = 0

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
	<br />
  <div class="field">
    Member ID<br />
    <%= f.text_field :member_id %>
  </div>
	<br />
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
	<br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<script>changeMenuTab("usersTab");</script>

<center>
	<h1>Users</h1>
	<%= link_to 'New User', new_user_path %><br /><br />

	<table align="center" cellpadding="6px">
	  <tr>
		<th align="left">ID</th>
	    <th align="left">Name</th>
	    <th align="left">Leagues</th>
	  </tr>

	<% @users.each do |user| %>
	  <tr>
		<td><%= user.member_id %></td>
	    <td><%= link_to user.name, user %></td>
		<td>
			<% for l in user.leagues %>
	    		| <%=	l.game %>:<%= Ranking.where(:user_id => user.id, :league_id => l.id)[0].ranking %>
			<% end %>
		</td>
	  </tr>
	<% end %>
	</table>
	<br />

</center>

app/views/users/new.html.erb
<h1>New user</h1>
<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Member Details</h1>

<p>
  <b>Name:</b>
  <%= @user.name %> <br />
  <b>Member ID:</b>
  <%= @user.member_id %> <br />
  <b>Email Address:</b>
  <%= @user.email %>
</p>
	
<p>
	<b>Leagues participating in:</b> <br />
	<% for l in @leagues %>
		<%= link_to l.game, l %> (<%= l.semester %> <%= l.year %>)
			Score: <%= Ranking.where(:user_id => @user.id, :league_id => l.id)[0].ranking %>
		<%= link_to "Remove from league", remove_from_league_user_path(:lid => l.id) %> <br />
	<% end %>
</p>
	
<p>
	<b>Enter another league:</b> <br />
	<% for l in @other_leagues %>
		<%= link_to l.game, l %> (<%= l.semester %> <%= l.year %>) 
		<%= link_to "Join league", join_league_user_path(:lid => l.id) %> <br />
	<% end %>
</p>
	

<br /><br /><br />

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Remove', @user, :confirm => 'Are you sure?', :method => :delete %> |
<%= link_to 'Back', users_path %>